"use client";

import React, { useState, useEffect, useMemo } from "react";
import Image from "next/image";
import { motion, AnimatePresence } from "framer-motion";
import CountUp from "@/components/animations/CountUp";
import SpotlightCard from "@/components/animations/SpotlightCard";
import Magnet from "@/components/animations/Magnet";
import { shortDate } from "@/utils/date";
import { fetchStudentEvaluations, StudentEvaluationItem } from "@/services/workflowService";
import { getAuthToken } from "@/utils/auth";
import { apiJson } from "@/services/apiClient";

export interface GeneratedReport {
  id: string;
  title: string;
  report_type: "japanese" | "manager";
  category_label: "Japanese Language Report" | "Manager Technical Report";
  cycle_type: "Quarterly" | "Annual";
  period: string;
  generated_by: string;
  generator_role: string;
  generator_avatar?: string;
  published_at: string;
  file_size: string;
  file_format: string;
  document_url?: string;
  score_percentage: number;
  grade_badge: string;
  executive_summary: string;
  competency_highlights: { label: string; score: number; max: number }[];
  key_achievements: string[];
  recommendations: string[];
}

// Initial reports generated by Manager and Teacher (configured for S3 linking in future)
const INITIAL_REPORTS: GeneratedReport[] = [
  {
    id: "rep-jp-q3-2026",
    title: "Q3 2026 Japanese Language Proficiency & Keigo Milestone Report",
    report_type: "japanese",
    category_label: "Japanese Language Report",
    cycle_type: "Quarterly",
    period: "Quarter 3 (Jul - Sep 2026)",
    generated_by: "Yuki Sato",
    generator_role: "Japanese Language Sensei & Faculty Lead",
    published_at: "2026-09-30",
    file_size: "2.8 MB",
    file_format: "PDF Document",
    document_url: "#",
    score_percentage: 91.5,
    grade_badge: "Grade A+ (Exceeds Target)",
    executive_summary:
      "Trainee demonstrated consistent progress across JLPT N5 and N4 milestones with superior mastery in business keigo and oral interview roleplays. Achieved 96% attendance and completed all scheduled vocabulary drill sessions on schedule.",
    competency_highlights: [
      { label: "Business Keigo & Formal Tone", score: 94, max: 100 },
      { label: "JLPT Kanji & Vocabulary Recall", score: 92, max: 100 },
      { label: "Listening & Workplace Comprehension", score: 90, max: 100 },
      { label: "Grammar & Written Syntax", score: 88, max: 100 },
    ],
    key_achievements: [
      "Passed all 6 weekly oral drills with an average score of 93.4%",
      "Mastered 250+ Kanji characters required for N4 progression",
      "Successfully delivered an 8-minute technical presentation entirely in Japanese",
    ],
    recommendations: [
      "Continue practicing sonkeigo (respectful forms) for client-facing engagements",
      "Focus on rapid audio reading comprehension for upcoming JLPT N3 certification",
    ],
  },
  {
    id: "rep-mgr-q3-2026",
    title: "Q3 2026 Technical Engineering & Sprint Velocity Appraisal Dossier",
    report_type: "manager",
    category_label: "Manager Technical Report",
    cycle_type: "Quarterly",
    period: "Quarter 3 (Jul - Sep 2026)",
    generated_by: "Dr. Hiroshi Tanaka",
    generator_role: "Reporting Manager & Lead Architect",
    published_at: "2026-09-28",
    file_size: "3.4 MB",
    file_format: "PDF Document",
    document_url: "#",
    score_percentage: 94.0,
    grade_badge: "Exceptional (Top 5%)",
    executive_summary:
      "Kanishka demonstrated outstanding engineering velocity across Next.js micro-frontends, FastAPI middleware, and PostgreSQL relational schemas. Refactored authentication workflows, improved test pass rate to 96%, and adhered strictly to delivery milestones.",
    competency_highlights: [
      { label: "Fullstack Architecture & Code Quality", score: 96, max: 100 },
      { label: "Problem Solving & Analytical Agility", score: 94, max: 100 },
      { label: "Sprint Delivery & Milestone Timeliness", score: 95, max: 100 },
      { label: "Documentation & Peer Code Review", score: 91, max: 100 },
    ],
    key_achievements: [
      "Completed 100% of assigned sprint tasks on or ahead of due dates",
      "Zero high-severity bugs introduced across production pull requests",
      "Implemented comprehensive self-evaluation rubrics and automated test suites",
    ],
    recommendations: [
      "Lead technical knowledge transfer session for junior onboarding cohorts",
      "Explore cloud infrastructure and Kubernetes pod autoscaling in upcoming Q4 sprint",
    ],
  },
  {
    id: "rep-jp-q2-2026",
    title: "Q2 2026 Mid-Year Japanese Linguistic Appraisal",
    report_type: "japanese",
    category_label: "Japanese Language Report",
    cycle_type: "Quarterly",
    period: "Quarter 2 (Apr - Jun 2026)",
    generated_by: "Yuki Sato",
    generator_role: "Japanese Language Sensei & Faculty Lead",
    published_at: "2026-06-30",
    file_size: "2.4 MB",
    file_format: "PDF Document",
    document_url: "#",
    score_percentage: 88.0,
    grade_badge: "Grade A (On Track)",
    executive_summary:
      "Mid-year review cleared successfully. Kanji foundation established with high pronunciation accuracy during live drills. Ready for advanced corporate roleplay.",
    competency_highlights: [
      { label: "Vocabulary Foundation", score: 90, max: 100 },
      { label: "Hiragana & Katakana Fluency", score: 98, max: 100 },
      { label: "Basic Conversational Keigo", score: 84, max: 100 },
      { label: "Classroom Participation", score: 92, max: 100 },
    ],
    key_achievements: [
      "Certified JLPT N5 Ready by academic dean",
      "100% attendance across morning language blocks",
    ],
    recommendations: [
      "Expand listening practice via business podcast recordings",
    ],
  },
  {
    id: "rep-mgr-annual-2025",
    title: "2025 Annual Trainee Performance Dossier & Gate Review",
    report_type: "manager",
    category_label: "Manager Technical Report",
    cycle_type: "Annual",
    period: "Annual Academic Year 2025",
    generated_by: "Dr. Hiroshi Tanaka",
    generator_role: "Reporting Manager & Lead Architect",
    published_at: "2025-12-22",
    file_size: "4.1 MB",
    file_format: "PDF Document",
    document_url: "#",
    score_percentage: 92.0,
    grade_badge: "Grade A+ (Distinction)",
    executive_summary:
      "Comprehensive annual review confirming high potential and readiness for advanced production engineering sprints. Commended by academic board.",
    competency_highlights: [
      { label: "Software Engineering Core", score: 93, max: 100 },
      { label: "Team Collaboration & Culture", score: 95, max: 100 },
      { label: "Milestone Attainment", score: 90, max: 100 },
    ],
    key_achievements: [
      "Honored in Top 10% Trainee Honors List",
      "Delivered sponsor showcase capstone project",
    ],
    recommendations: [
      "Transition into fullstack production workflow lead in 2026",
    ],
  },
];

export default function StudentReportsPage() {
  const [reports, setReports] = useState<GeneratedReport[]>(INITIAL_REPORTS);
  const [reportTypeFilter, setReportTypeFilter] = useState<"all" | "japanese" | "manager">("all");
  const [cycleFilter, setCycleFilter] = useState<"all" | "Quarterly" | "Annual">("all");
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedReport, setSelectedReport] = useState<GeneratedReport | null>(null);
  const [downloadNotice, setDownloadNotice] = useState<string | null>(null);

  // Load live evaluations and reports on mount
  useEffect(() => {
    const loadLiveReports = async () => {
      try {
        const token = getAuthToken();
        const headers = {
          Accept: "application/json",
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        };

        const [evalsRes, jpRes] = await Promise.allSettled([
          fetchStudentEvaluations(),
          apiJson<any>("/api/v1/student/japanese-analytics"),
        ]);

        const liveList: GeneratedReport[] = [];

        // Map manager/general evaluations
        if (evalsRes.status === "fulfilled" && evalsRes.value?.items) {
          evalsRes.value.items.forEach((ev: StudentEvaluationItem) => {
            const isJp = (ev.evaluation_type || "").toLowerCase().includes("japanese");
            const pct =
              ev.percentage ??
              (ev.max_score && ev.total_score ? Math.round((ev.total_score / ev.max_score) * 100) : 85);
            liveList.push({
              id: `eval-${ev.id}`,
              title: ev.task_title
                ? `${ev.task_title} Assessment Dossier`
                : `${ev.workflow_title || "Performance"} Milestone Report`,
              report_type: isJp ? "japanese" : "manager",
              category_label: isJp ? "Japanese Language Report" : "Manager Technical Report",
              cycle_type: "Quarterly",
              period: ev.evaluated_at
                ? new Date(ev.evaluated_at).toLocaleDateString("en-US", { month: "short", year: "numeric" })
                : "Current Quarter",
              generated_by: ev.evaluator_name || (isJp ? "Japanese Faculty" : "Reporting Manager"),
              generator_role: isJp ? "Language Faculty Mentor" : "Technical Lead & Manager",
              published_at: ev.evaluated_at ? ev.evaluated_at.split("T")[0] : new Date().toISOString().split("T")[0],
              file_size: "1.9 MB",
              file_format: "PDF Document",
              score_percentage: pct,
              grade_badge: pct >= 90 ? "Grade A+ (Exceeds Target)" : pct >= 80 ? "Grade A (Proficient)" : "Grade B (Developing)",
              executive_summary: ev.remarks || "Comprehensive milestone evaluation performance audit.",
              competency_highlights: (ev.metrics || []).map((m) => ({
                label: m.name,
                score: m.score ?? 80,
                max: m.max_score || m.full_score || 100,
              })),
              key_achievements: ["Successfully completed assigned milestone assessment"],
              recommendations: ["Continue tracking against curriculum targets"],
            });
          });
        }

        // Map Japanese evaluations history
        if (jpRes.status === "fulfilled" && jpRes.value?.evaluations_history) {
          jpRes.value.evaluations_history.forEach((jpEv: any) => {
            liveList.push({
              id: `jp-${jpEv.id}`,
              title: `${jpEv.evaluation_title || "JLPT Milestone"} Official Evaluation`,
              report_type: "japanese",
              category_label: "Japanese Language Report",
              cycle_type: "Quarterly",
              period: jpEv.evaluation_date
                ? new Date(jpEv.evaluation_date).toLocaleDateString("en-US", { month: "short", year: "numeric" })
                : "Recent Milestone",
              generated_by: "Japanese Language Sensei",
              generator_role: "Japanese Language Faculty Lead",
              published_at: jpEv.evaluation_date || new Date().toISOString().split("T")[0],
              file_size: "2.1 MB",
              file_format: "PDF Document",
              score_percentage: jpEv.percentage || 85,
              grade_badge: (jpEv.percentage || 85) >= 90 ? "Grade A+ (Distinction)" : "Grade A (Proficient)",
              executive_summary: jpEv.feedback || "Evaluated by sensei on Japanese language retention.",
              competency_highlights: [
                { label: `JLPT ${jpEv.jlpt_level || "N5"} Proficiency`, score: jpEv.percentage || 85, max: 100 },
              ],
              key_achievements: [`Completed ${jpEv.evaluation_type || "daily"} assessment`],
              recommendations: ["Maintain consistent flashcard and kanji practice"],
            });
          });
        }

        if (liveList.length > 0) {
          setReports([...liveList, ...INITIAL_REPORTS]);
        }
      } catch (err) {
        console.warn("Failed to load live reports:", err);
      }
    };

    loadLiveReports();
  }, []);

  // Filter reports
  const filteredReports = useMemo(() => {
    return reports.filter((r) => {
      if (reportTypeFilter !== "all" && r.report_type !== reportTypeFilter) return false;
      if (cycleFilter !== "all" && r.cycle_type !== cycleFilter) return false;
      if (searchQuery.trim()) {
        const query = searchQuery.toLowerCase();
        const matchesTitle = r.title.toLowerCase().includes(query);
        const matchesAuthor = r.generated_by.toLowerCase().includes(query);
        const matchesPeriod = r.period.toLowerCase().includes(query);
        const matchesSummary = r.executive_summary.toLowerCase().includes(query);
        if (!matchesTitle && !matchesAuthor && !matchesPeriod && !matchesSummary) return false;
      }
      return true;
    });
  }, [reports, reportTypeFilter, cycleFilter, searchQuery]);

  // Handle mock PDF / S3 download
  const handleDownload = (report: GeneratedReport, e: React.MouseEvent) => {
    e.stopPropagation();
    setDownloadNotice(`Downloading "${report.title}" (${report.file_size})...`);
    setTimeout(() => {
      setDownloadNotice(`Report "${report.title}" downloaded successfully.`);
      setTimeout(() => setDownloadNotice(null), 3000);
    }, 1200);
  };

  const handlePrint = (report: GeneratedReport, e: React.MouseEvent) => {
    e.stopPropagation();
    setSelectedReport(report);
    setTimeout(() => {
      window.print();
    }, 300);
  };

  // KPIs
  const totalCount = reports.length;
  const japaneseCount = reports.filter((r) => r.report_type === "japanese").length;
  const managerCount = reports.filter((r) => r.report_type === "manager").length;
  const avgOverallScore =
    totalCount > 0
      ? (reports.reduce((acc, r) => acc + r.score_percentage, 0) / totalCount).toFixed(1)
      : "0";

  return (
    <div className="space-y-6 pb-16">
      
      {/* Toast Download Feedback */}
      <AnimatePresence>
        {downloadNotice && (
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="p-4 rounded-2xl bg-indigo-50 border border-indigo-200 text-indigo-950 flex items-center justify-between shadow-lg"
          >
            <div className="flex items-center gap-3">
              <span className="material-symbols-outlined text-primary text-xl">cloud_download</span>
              <p className="text-xs font-semibold">{downloadNotice}</p>
            </div>
            <button
              onClick={() => setDownloadNotice(null)}
              className="text-xs font-bold uppercase tracking-wider px-2 py-1 rounded hover:bg-black/5"
            >
              Dismiss
            </button>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Top Header Section */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white p-6 sm:p-7 rounded-3xl border border-slate-200/80 shadow-xs">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="px-2.5 py-0.5 bg-primary/10 text-primary text-xs font-bold rounded-lg uppercase tracking-wider">
              Official Dossiers
            </span>
            <span className="text-xs text-slate-500 font-medium">Quarterly &amp; Annual Reports</span>
          </div>
          <h1 className="font-headline font-bold text-2xl sm:text-3xl text-slate-900 tracking-tight">
            Generated Performance Reports
          </h1>
          <p className="text-sm text-slate-600 mt-1 max-w-2xl">
            Access formal performance reports created by your reporting manager and Japanese language teacher. Inspect detailed rubric attainment, executive summaries, and download official PDF records.
          </p>
        </div>

        <div className="flex items-center gap-3 self-start sm:self-center">
          <div className="text-right hidden sm:block">
            <span className="text-xs text-slate-500 block font-medium">Published Dossiers</span>
            <span className="text-xl font-bold text-primary font-mono">
              <CountUp to={totalCount} duration={1.2} suffix=" Files" />
            </span>
          </div>
          <div className="w-14 h-14 rounded-2xl bg-primary text-white flex flex-col items-center justify-center font-mono font-bold text-base shadow-sm shrink-0">
            <span>{totalCount}</span>
            <span className="text-[10px] font-normal opacity-80">Reports</span>
          </div>
        </div>
      </div>

      {/* 4 Summary Stat Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        
        {/* Card 1: Total Generated Reports */}
        <SpotlightCard
          spotlightColor="rgba(75, 46, 245, 0.08)"
          className="bg-white p-5 rounded-2xl border border-slate-200/80 flex flex-col justify-between shadow-xs"
        >
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs font-semibold text-slate-500">All Published Reports</span>
            <div className="w-8 h-8 rounded-xl bg-indigo-50 text-indigo-700 flex items-center justify-center">
              <span className="material-symbols-outlined text-base">description</span>
            </div>
          </div>
          <div>
            <div className="text-2xl sm:text-3xl font-bold text-slate-900 font-headline">
              <CountUp to={totalCount} duration={1.2} />
            </div>
            <p className="text-xs text-slate-500 mt-1">Official quarterly &amp; annual files</p>
          </div>
        </SpotlightCard>

        {/* Card 2: Japanese Reports */}
        <SpotlightCard
          spotlightColor="rgba(16, 185, 129, 0.08)"
          className="bg-white p-5 rounded-2xl border border-slate-200/80 flex flex-col justify-between shadow-xs"
        >
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs font-semibold text-slate-500">Japanese Language Reports</span>
            <div className="w-8 h-8 rounded-xl bg-emerald-50 text-emerald-700 flex items-center justify-center">
              <span className="material-symbols-outlined text-base">translate</span>
            </div>
          </div>
          <div>
            <div className="text-2xl sm:text-3xl font-bold text-slate-900 font-headline">
              <CountUp to={japaneseCount} duration={1.2} />
            </div>
            <p className="text-xs text-emerald-700 font-medium mt-1">Teacher / Sensei Generated</p>
          </div>
        </SpotlightCard>

        {/* Card 3: Manager Reports */}
        <SpotlightCard
          spotlightColor="rgba(59, 130, 246, 0.08)"
          className="bg-white p-5 rounded-2xl border border-slate-200/80 flex flex-col justify-between shadow-xs"
        >
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs font-semibold text-slate-500">Manager Technical Reports</span>
            <div className="w-8 h-8 rounded-xl bg-blue-50 text-blue-700 flex items-center justify-center">
              <span className="material-symbols-outlined text-base">engineering</span>
            </div>
          </div>
          <div>
            <div className="text-2xl sm:text-3xl font-bold text-slate-900 font-headline">
              <CountUp to={managerCount} duration={1.2} />
            </div>
            <p className="text-xs text-blue-700 font-medium mt-1">Tech Lead / Manager Generated</p>
          </div>
        </SpotlightCard>

        {/* Card 4: Cumulative Composite Score */}
        <SpotlightCard
          spotlightColor="rgba(245, 158, 11, 0.08)"
          className="bg-white p-5 rounded-2xl border border-slate-200/80 flex flex-col justify-between shadow-xs"
        >
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs font-semibold text-slate-500">Cumulative Average</span>
            <div className="w-8 h-8 rounded-xl bg-amber-50 text-amber-700 flex items-center justify-center">
              <span className="material-symbols-outlined text-base">verified</span>
            </div>
          </div>
          <div>
            <div className="text-2xl sm:text-3xl font-bold text-slate-900 font-headline">
              <CountUp to={Number(avgOverallScore)} duration={1.2} decimals={1} suffix="%" />
            </div>
            <p className="text-xs text-amber-700 font-medium mt-1">Grade A+ Performance</p>
          </div>
        </SpotlightCard>

      </div>

      {/* Reports Gallery & Control Bar */}
      <div className="bg-white rounded-3xl border border-slate-200/80 p-6 sm:p-7 shadow-xs">
        
        {/* Controls Bar */}
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 pb-6 border-b border-slate-100">
          <div>
            <h2 className="text-xl font-bold text-slate-900 font-headline">
              Generated Reports Archive
            </h2>
            <p className="text-xs sm:text-sm text-slate-500 mt-0.5">
              Filtered by report type, evaluation cycle, or keywords
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-2 sm:gap-3">
            {/* Search */}
            <div className="relative flex-1 sm:flex-initial">
              <span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 text-lg">
                search
              </span>
              <input
                type="text"
                placeholder="Search reports..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full sm:w-52 pl-9 pr-3 py-1.5 rounded-xl bg-slate-50 border border-slate-200 text-xs sm:text-sm text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary"
              />
            </div>

            {/* Report Type Tabs */}
            <div className="flex items-center gap-1 bg-slate-100 p-1 rounded-xl border border-slate-200/60 overflow-x-auto">
              {[
                { id: "all", label: "All Reports" },
                { id: "japanese", label: "Japanese Reports" },
                { id: "manager", label: "Manager Reports" },
              ].map((tab) => (
                <button
                  key={tab.id}
                  onClick={() => setReportTypeFilter(tab.id as any)}
                  className={`px-3 py-1 rounded-lg text-xs font-semibold whitespace-nowrap transition-all ${
                    reportTypeFilter === tab.id
                      ? "bg-white text-primary shadow-xs"
                      : "text-slate-600 hover:text-slate-900"
                  }`}
                >
                  {tab.label}
                </button>
              ))}
            </div>

            {/* Cycle Filter */}
            <select
              value={cycleFilter}
              onChange={(e) => setCycleFilter(e.target.value as any)}
              className="bg-slate-50 border border-slate-200 px-3 py-1.5 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-primary/20 cursor-pointer"
            >
              <option value="all">All Cycles</option>
              <option value="Quarterly">Quarterly Only</option>
              <option value="Annual">Annual Only</option>
            </select>
          </div>
        </div>

        {/* Reports Grid */}
        <div className="pt-6">
          {filteredReports.length === 0 ? (
            <div className="py-20 text-center text-slate-500 space-y-3 bg-slate-50/50 rounded-2xl border border-dashed border-slate-200">
              <div className="w-14 h-14 rounded-full bg-slate-100 text-slate-400 flex items-center justify-center mx-auto">
                <span className="material-symbols-outlined text-3xl">folder_off</span>
              </div>
              <div>
                <h3 className="text-base font-bold text-slate-800">No generated reports found</h3>
                <p className="text-xs text-slate-500 max-w-md mx-auto mt-1">
                  When your manager or teacher manually compiles a quarterly appraisal or annual review dossier, it will appear here for download and inspection.
                </p>
              </div>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              {filteredReports.map((report) => {
                const isJapanese = report.report_type === "japanese";

                return (
                  <div
                    key={report.id}
                    onClick={() => setSelectedReport(report)}
                    className="bg-white border border-slate-200/90 hover:border-primary/40 rounded-2xl p-6 shadow-xs hover:shadow-md transition-all flex flex-col justify-between cursor-pointer group"
                  >
                    <div>
                      {/* Top Badges */}
                      <div className="flex items-center justify-between gap-2 mb-3">
                        <span
                          className={`text-[10px] font-bold uppercase tracking-wider px-2.5 py-0.5 rounded-md border ${
                            isJapanese
                              ? "bg-emerald-50 text-emerald-700 border-emerald-200"
                              : "bg-indigo-50 text-indigo-700 border-indigo-200"
                          }`}
                        >
                          {report.category_label}
                        </span>

                        <span className="text-xs font-mono font-bold text-slate-900 bg-slate-100 px-2.5 py-0.5 rounded-full">
                          {report.cycle_type} · {report.period.split(" ")[0]}
                        </span>
                      </div>

                      {/* Title */}
                      <h3 className="font-bold text-base text-slate-900 group-hover:text-primary transition-colors leading-snug mb-2">
                        {report.title}
                      </h3>

                      {/* Executive Summary */}
                      <p className="text-xs text-slate-600 leading-relaxed line-clamp-3 mb-4">
                        {report.executive_summary}
                      </p>

                      {/* Author & Score Highlights */}
                      <div className="bg-slate-50/80 p-3.5 rounded-xl border border-slate-100 mb-4 space-y-2">
                        <div className="flex items-center justify-between text-xs">
                          <span className="text-slate-500">Author:</span>
                          <span className="font-bold text-slate-800">{report.generated_by} ({report.generator_role.split(" ")[0]})</span>
                        </div>
                        <div className="flex items-center justify-between text-xs">
                          <span className="text-slate-500">Attainment Score:</span>
                          <span className="font-mono font-bold text-primary text-sm">
                            {report.score_percentage}% · <span className="text-xs font-semibold text-emerald-600">{report.grade_badge.split(" ")[0]}</span>
                          </span>
                        </div>
                      </div>
                    </div>

                    {/* Footer & Actions */}
                    <div className="pt-3 border-t border-slate-100 flex items-center justify-between gap-2">
                      <div className="flex items-center gap-1.5 text-xs text-slate-400">
                        <span className="material-symbols-outlined text-sm">picture_as_pdf</span>
                        <span>{report.file_size}</span>
                        <span>•</span>
                        <span>{shortDate(report.published_at)}</span>
                      </div>

                      <div className="flex items-center gap-2">
                        <button
                          type="button"
                          onClick={(e) => handlePrint(report, e)}
                          title="Print Document"
                          className="p-1.5 rounded-lg text-slate-500 hover:text-slate-900 hover:bg-slate-100 transition-colors"
                        >
                          <span className="material-symbols-outlined text-base">print</span>
                        </button>

                        <button
                          type="button"
                          onClick={(e) => handleDownload(report, e)}
                          className="px-3 py-1.5 bg-primary/10 hover:bg-primary text-primary hover:text-white rounded-xl text-xs font-semibold transition-all flex items-center gap-1 border border-primary/20"
                        >
                          <span className="material-symbols-outlined text-sm">download</span>
                          <span>Download PDF</span>
                        </button>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

      </div>

      {/* Modal / Detailed Report Viewer */}
      <AnimatePresence>
        {selectedReport && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-xs overflow-y-auto">
            <motion.div
              initial={{ opacity: 0, scale: 0.96, y: 10 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.96, y: 10 }}
              className="bg-white rounded-3xl p-6 sm:p-8 max-w-3xl w-full border border-slate-200 shadow-2xl my-8 space-y-6 max-h-[90vh] overflow-y-auto"
            >
              {/* Report Document Header */}
              <div className="flex items-start justify-between pb-6 border-b border-slate-200">
                <div className="flex items-center gap-3">
                  <Image
                    alt="Dailoqa"
                    src="/dailoqa_logo.png"
                    width={110}
                    height={30}
                    className="h-7 w-auto object-contain"
                  />
                  <div className="border-l border-slate-300 pl-3">
                    <span className="text-xs font-mono font-bold text-slate-900 uppercase">
                      Official Appraisal Dossier
                    </span>
                    <p className="text-[11px] text-slate-500">Archived Document · Verification ID #{selectedReport.id}</p>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={() => setSelectedReport(null)}
                  className="p-1.5 rounded-xl text-slate-400 hover:bg-slate-100 hover:text-slate-700 transition-colors"
                >
                  <span className="material-symbols-outlined">close</span>
                </button>
              </div>

              {/* Title & Metadata Banner */}
              <div className="bg-slate-50/80 p-5 rounded-2xl border border-slate-200/80 space-y-3">
                <div className="flex items-center gap-2 flex-wrap">
                  <span className={`text-[11px] font-bold uppercase tracking-wider px-2.5 py-0.5 rounded-md border ${
                    selectedReport.report_type === "japanese"
                      ? "bg-emerald-50 text-emerald-700 border-emerald-200"
                      : "bg-indigo-50 text-indigo-700 border-indigo-200"
                  }`}>
                    {selectedReport.category_label}
                  </span>
                  <span className="text-xs font-semibold text-slate-600 bg-white px-2.5 py-0.5 rounded border border-slate-200">
                    Cycle: {selectedReport.period}
                  </span>
                  <span className="text-xs font-semibold text-slate-600 bg-white px-2.5 py-0.5 rounded border border-slate-200">
                    Published: {shortDate(selectedReport.published_at)}
                  </span>
                </div>

                <h2 className="text-xl sm:text-2xl font-bold font-headline text-slate-900">
                  {selectedReport.title}
                </h2>

                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pt-2 border-t border-slate-200/60">
                  <div className="text-xs">
                    <span className="text-slate-500">Evaluator / Author: </span>
                    <strong className="text-slate-900">{selectedReport.generated_by}</strong> ({selectedReport.generator_role})
                  </div>
                  <div className="text-right">
                    <span className="text-xs font-bold text-slate-500 uppercase tracking-wider mr-2">Overall Grade:</span>
                    <span className="text-lg font-bold font-mono text-primary">{selectedReport.score_percentage}%</span>
                    <span className="text-xs font-bold text-emerald-700 ml-1.5 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200">
                      {selectedReport.grade_badge}
                    </span>
                  </div>
                </div>
              </div>

              {/* Section 1: Executive Summary */}
              <div>
                <h3 className="text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">
                  1. Executive Summary &amp; Milestone Attainment
                </h3>
                <p className="text-xs sm:text-sm text-slate-700 leading-relaxed bg-white p-4 rounded-xl border border-slate-200">
                  {selectedReport.executive_summary}
                </p>
              </div>

              {/* Section 2: Rubric Competency Breakdown */}
              <div>
                <h3 className="text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">
                  2. Competency Rubrics &amp; Attainment Breakdown
                </h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {selectedReport.competency_highlights.map((comp) => (
                    <div key={comp.label} className="p-3.5 rounded-xl bg-slate-50 border border-slate-200/80 space-y-1.5">
                      <div className="flex justify-between text-xs font-semibold text-slate-800">
                        <span>{comp.label}</span>
                        <span className="font-mono font-bold text-primary">{comp.score} / {comp.max}</span>
                      </div>
                      <div className="w-full bg-slate-200 h-2 rounded-full overflow-hidden">
                        <div
                          className="bg-primary h-full rounded-full transition-all duration-500"
                          style={{ width: `${(comp.score / comp.max) * 100}%` }}
                        />
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Section 3: Key Achievements & Recommendations */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="p-4 rounded-xl bg-emerald-50/50 border border-emerald-100 space-y-2">
                  <h4 className="text-xs font-bold text-emerald-800 uppercase tracking-wider flex items-center gap-1">
                    <span className="material-symbols-outlined text-sm">check_circle</span>
                    Key Achievements
                  </h4>
                  <ul className="text-xs text-slate-700 space-y-1.5 list-disc pl-4">
                    {selectedReport.key_achievements.map((ach, idx) => (
                      <li key={idx}>{ach}</li>
                    ))}
                  </ul>
                </div>

                <div className="p-4 rounded-xl bg-indigo-50/50 border border-indigo-100 space-y-2">
                  <h4 className="text-xs font-bold text-indigo-800 uppercase tracking-wider flex items-center gap-1">
                    <span className="material-symbols-outlined text-sm">lightbulb</span>
                    Growth Recommendations
                  </h4>
                  <ul className="text-xs text-slate-700 space-y-1.5 list-disc pl-4">
                    {selectedReport.recommendations.map((rec, idx) => (
                      <li key={idx}>{rec}</li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Modal Footer Actions */}
              <div className="flex items-center justify-between pt-4 border-t border-slate-200">
                <span className="text-xs text-slate-400 font-mono">
                  S3 Link Archive • {selectedReport.file_format} • {selectedReport.file_size}
                </span>

                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={(e) => handlePrint(selectedReport, e)}
                    className="px-4 py-2 rounded-xl text-xs font-semibold text-slate-700 hover:bg-slate-100 border border-slate-200 flex items-center gap-1.5"
                  >
                    <span className="material-symbols-outlined text-sm">print</span>
                    <span>Print Dossier</span>
                  </button>

                  <button
                    type="button"
                    onClick={(e) => handleDownload(selectedReport, e)}
                    className="px-5 py-2 rounded-xl bg-primary hover:bg-primary/90 text-white text-xs font-semibold shadow-xs flex items-center gap-1.5"
                  >
                    <span className="material-symbols-outlined text-sm">download</span>
                    <span>Download PDF</span>
                  </button>
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

    </div>
  );
}
