import {
  OrganisationRecord,
  UserDirectoryRecord,
  AuditLogRecord,
  ProgressIncident,
} from "./types";

export const MOCK_ORGANISATIONS: OrganisationRecord[] = [
  {
    id: "org-1",
    code: "MLI",
    name: "MiRai Language Institute",
    domain: "mirai.ac.jp",
    region: "Tokyo, JP",
    plan: "Enterprise",
    status: "Active",
    totalUsers: 480,
    maxUsers: 500,
    storageGB: 340,
    maxStorageGB: 500,
    adminName: "Prof. Arthur Vance",
    adminEmail: "vance@mirai.ac.jp",
    mfaEnforced: true,
    createdAt: "2024-03-15",
  },
  {
    id: "org-2",
    code: "GTI",
    name: "Global Tech Innovations",
    domain: "globaltech.io",
    region: "Yokohama, JP",
    plan: "Enterprise",
    status: "Active",
    totalUsers: 220,
    maxUsers: 250,
    storageGB: 185,
    maxStorageGB: 300,
    adminName: "Elena Rostova",
    adminEmail: "e.rostova@globaltech.io",
    mfaEnforced: true,
    createdAt: "2024-06-01",
  },
  {
    id: "org-3",
    code: "KDA",
    name: "Kyoto Digital Academy",
    domain: "kyotodigital.edu",
    region: "Kyoto, JP",
    plan: "Academic",
    status: "Active",
    totalUsers: 140,
    maxUsers: 200,
    storageGB: 95,
    maxStorageGB: 200,
    adminName: "Samantha Vance",
    adminEmail: "s.vance@kyotodigital.edu",
    mfaEnforced: false,
    createdAt: "2024-09-10",
  },
  {
    id: "org-4",
    code: "NOC",
    name: "NeoTech Osaka Consortium",
    domain: "neotech-osaka.co.jp",
    region: "Osaka, JP",
    plan: "Standard",
    status: "Suspended",
    totalUsers: 85,
    maxUsers: 100,
    storageGB: 45,
    maxStorageGB: 100,
    adminName: "Kenji Sato",
    adminEmail: "k.sato@neotech-osaka.co.jp",
    mfaEnforced: false,
    createdAt: "2024-01-20",
  },
];

export const MOCK_USERS: UserDirectoryRecord[] = [
  {
    id: "usr-1",
    name: "Kanishka Sharma",
    email: "k.sharma@mirai.ac.jp",
    role: "Learner",
    organisation: "MiRai Language Institute",
    orgCode: "MLI",
    batchOrDept: "Batch 2026-Alpha",
    specialization: "JLPT Track N2",
    status: "Active",
    mfaEnabled: true,
    lastActive: "14 mins ago",
    initials: "KS",
  },
  {
    id: "usr-2",
    name: "Prof. Arthur Vance",
    email: "vance@mirai.ac.jp",
    role: "Teacher",
    organisation: "MiRai Language Institute",
    orgCode: "MLI",
    batchOrDept: "Faculty Lead",
    specialization: "Linguistics & Pedagogy",
    status: "Active",
    mfaEnabled: true,
    lastActive: "Today, 08:30 AM",
    initials: "AV",
  },
  {
    id: "usr-3",
    name: "Elena Rostova",
    email: "e.rostova@globaltech.io",
    role: "HR Manager",
    organisation: "Global Tech Innovations",
    orgCode: "GTI",
    batchOrDept: "People Operations",
    specialization: "Talent Governance",
    status: "Active",
    mfaEnabled: true,
    lastActive: "1 hour ago",
    initials: "ER",
  },
  {
    id: "usr-4",
    name: "Kenji Sato",
    email: "k.sato@neotech-osaka.co.jp",
    role: "Manager",
    organisation: "NeoTech Osaka Consortium",
    orgCode: "NOC",
    batchOrDept: "Engineering Ops",
    specialization: "Performance Oversight",
    status: "Suspended",
    mfaEnabled: false,
    lastActive: "Yesterday",
    initials: "KS",
  },
  {
    id: "usr-5",
    name: "Samantha Vance",
    email: "s.vance@kyotodigital.edu",
    role: "HR Manager",
    organisation: "Kyoto Digital Academy",
    orgCode: "KDA",
    batchOrDept: "Academic Administration",
    specialization: "Curriculum HR",
    status: "Active",
    mfaEnabled: true,
    lastActive: "2 hours ago",
    initials: "SV",
  },
  {
    id: "usr-6",
    name: "Taro Yamada",
    email: "t.yamada@mirai.ac.jp",
    role: "Learner",
    organisation: "MiRai Language Institute",
    orgCode: "MLI",
    batchOrDept: "Batch 2026-Beta",
    specialization: "Business Japanese N1",
    status: "Pending",
    mfaEnabled: false,
    lastActive: "3 days ago",
    initials: "TY",
  },
];

export const MOCK_AUDIT_LOGS: AuditLogRecord[] = [
  {
    id: "aud-1",
    hash: "#e3b0c442",
    timestamp: "14:15:22 UTC",
    relativeTime: "15m ago",
    orgName: "MiRai Language Inst.",
    orgCode: "MLI",
    actorName: "Marcus Brody",
    actorRole: "SUPERUSER",
    impersonatedBy: "Elena Rostova (HR Manager)",
    actionTitle: "View As Session #VAS-9921",
    actionDetails: "4 write actions blocked by read-only policy",
    ipAddress: "103.21.244.0",
    location: "Tokyo VPN · Firefox/Linux",
    severity: "info",
    payloadJson: {
      session_type: "view_as_simulation",
      enforced_sandbox: true,
      simulated_user: "Elena Rostova",
      target_tenant: "ORG-1002",
      kernel_override: true,
    },
  },
  {
    id: "aud-2",
    hash: "#a48b9911",
    timestamp: "11:42:10 UTC",
    relativeTime: "3h ago",
    orgName: "Kyoto Digital Academy",
    orgCode: "KDA",
    actorName: "Samantha Vance",
    actorRole: "HR Manager",
    actionTitle: "Weightage Change #RUB-KYOTO-N2",
    actionDetails: "Oral Exam weightage: 25% ➔ 30%",
    ipAddress: "133.242.18.90",
    location: "Kyoto, JP · Safari / iPad",
    severity: "warning",
    payloadJson: {
      rubric_id: "RUB-KYOTO-N2",
      field_modified: "oral_exam_weight",
      old_value: 0.25,
      new_value: 0.3,
    },
  },
  {
    id: "aud-3",
    hash: "#fc0991c2",
    timestamp: "18:20:00 UTC",
    relativeTime: "Yesterday",
    orgName: "NeoTech Osaka Consort.",
    orgCode: "NOC",
    actorName: "Marcus Brody",
    actorRole: "SUPERUSER",
    actionTitle: "Org Suspended #ORG-8820",
    actionDetails: "Freeze: unpaid invoices & compliance lapse",
    ipAddress: "103.21.244.0",
    location: "Tokyo Platform HQ (Internal)",
    severity: "critical",
    payloadJson: {
      org_id: "ORG-8820",
      reason: "compliance_audit_failed",
      action: "tenant_lockout",
      grace_period_days: 0,
    },
  },
  {
    id: "aud-4",
    hash: "#7b91d4e0",
    timestamp: "09:12:04 UTC",
    relativeTime: "Yesterday",
    orgName: "Global Tech Innovations",
    orgCode: "GTI",
    actorName: "Elena Rostova",
    actorRole: "HR Manager",
    actionTitle: "Batch Promotion Finalized",
    actionDetails: "Promoted 42 engineers to Japanese Level B2",
    ipAddress: "133.152.88.12",
    location: "Yokohama, JP · Chrome/macOS",
    severity: "info",
    payloadJson: {
      batch_id: "BATCH-2025-DEV",
      students_count: 42,
      evaluation_cycle: "Q3-2026",
    },
  },
];

export const MOCK_INCIDENTS: ProgressIncident[] = [
  {
    id: "inc-1",
    targetName: "Kanishka Sharma",
    targetRole: "Learner",
    orgName: "MiRai Language Institute",
    severity: "medium",
    issueTitle: "Vocabulary Velocity Stagnation",
    issueDescription: "Flashcard quiz completion dropped by 45% in Week 8. JLPT N2 Kanji pace behind milestone.",
    metricLabel: "Active Gap",
    metricValue: "-18 Kanji Cards",
    recommendedAction: "Notify Mentor Prof. Arthur Vance for supplemental 1:1 oral session",
  },
  {
    id: "inc-2",
    targetName: "Prof. Arthur Vance",
    targetRole: "Teacher",
    orgName: "MiRai Language Institute",
    severity: "high",
    issueTitle: "14 Overdue Milestone Evaluations",
    issueDescription: "Batch 2026-Alpha midterm grading pending for > 7 business days past SLA.",
    metricLabel: "Pending Reviews",
    metricValue: "14 Overdue",
    recommendedAction: "Send automated priority reminder & re-assign 4 evals to secondary faculty",
  },
  {
    id: "inc-3",
    targetName: "Global Tech Innovations",
    targetRole: "HR",
    orgName: "Global Tech Innovations",
    severity: "medium",
    issueTitle: "Q3 Evaluation Cycle Lockout Near Deadline",
    issueDescription: "38% of employee self-evaluations unsubmitted 48 hours before cycle close.",
    metricLabel: "Unsubmitted Ratio",
    metricValue: "38% Incomplete",
    recommendedAction: "Issue cross-tenant HR reminder broadcast across Slack & Microsoft Teams",
  },
];

export const MOCK_TEAMS_MEETINGS = [
  {
    id: "tm-1",
    title: "JLPT N2 Oral Assessment Panel",
    org: "MiRai Language Institute",
    mentor: "Prof. Arthur Vance",
    participants: 6,
    duration: "45 mins",
    time: "Today, 10:00 AM",
    status: "Completed",
    recordingUrl: "https://teams.microsoft.com",
  },
  {
    id: "tm-2",
    title: "Engineering Cohort Weekly Sync",
    org: "Global Tech Innovations",
    mentor: "Elena Rostova",
    participants: 18,
    duration: "60 mins",
    time: "Today, 02:00 PM",
    status: "In Progress",
    recordingUrl: "https://teams.microsoft.com",
  },
  {
    id: "tm-3",
    title: "Curriculum Review & Rubric Calibration",
    org: "Kyoto Digital Academy",
    mentor: "Samantha Vance",
    participants: 8,
    duration: "30 mins",
    time: "Tomorrow, 09:30 AM",
    status: "Scheduled",
    recordingUrl: "https://teams.microsoft.com",
  },
];
